language: boa
script: ant -Dprotobuf.uptodate=true test checkstyle
notifications:
  email:
    recipients:
      - hridesh@iastate.edu
      - rdyer@iastate.edu
    on_success: change
    on_failure: always
